### ISSUE TITLE
FR: write IPs to hosts.deny

### ISSUE THREAD

**Issue by goldencut** [vab/torblock#1]
Hi,
Could it be made to write received IPs to hosts.deny instead (or some other, user-choosable file so for example web server could use it)?

**Comment by vab** [comment]
Hi, 

The feature that you requested has been added to the program. The script now supports TCP Wrappers, nginx, Apache v2.4 require format, and the depricated Apache allow/deny format.

I would recommend not using TCP Wrappers (hosts.deny). That program has not been updated in a very log time and it is no longer maintained. While the code does continue to work, it is not guaranteed to be updated if it becomes incompatible with the the Linux kernel or networking stack. It will also have lower performance than the more modern firewalling systems built into Linux.

   - Alex
